version: "3"
services:
  app:
    image: gotodo
    build:
      args:
        - target=dev
    environment:
      TODO_ENV: dev
      PORT: 8080
    volumes:
        - .:/app
    ports:
        - "1800:8080"
